### ISSUE TITLE
make integration test failing

### ISSUE THREAD

**Issue by theresac23** [envoyproxy/go-control-plane#331] opened 2020-07-28 19:34 UTC
When running ./build/run_docker.sh make integration it passes the xds tests but then gives an error on `kill ${ENVOY_PID}`:

`2020/07/28 19:19:36 upstream listening HTTP/1.1 on 18080
2020/07/28 19:19:37 waiting for the first request...
2020/07/28 19:19:37 gateway listening HTTP/1.1 on 18001
2020/07/28 19:19:37 management server listening on 18000
2020/07/28 19:19:37 access log server listening on 18090
2020/07/28 19:20:37 timeout waiting for the first request
build/integration.sh: line 40: kill: (1177) - No such process
Makefile:58: recipe for target 'integration.xds.v3' failed
make: *** [integration.xds.v3] Error 1`

(I have pulled the latest update.)

**Comment by kyessenov** [comment] 2020-07-28 23:53
@acnodal-tc can you take a look?

**Comment by acnodal-tc** [comment] 2020-07-29 12:37
Looks like Envoy is exiting, both because the tests never get a response from upstream and because the Envoy process is no longer there to be killed.  @theresac23 could you please paste the entire output of the "./build/run_docker.sh make integration" command into a gist so I can take a look?  Thanks!

**Comment by acnodal-tc** [comment] 2020-07-29 12:43
FYI @theresac23 the tests configure Envoy to write its logs to files in the project root directory, e.g., envoy.xdsv3.log, envoy.ads.log etc.  You might find something useful in those logs since it looks like Envoy is exiting.

**Comment by theresac23** [comment] 2020-07-29 16:27
Hi @acnodal-tc thanks for your response. This is has the output of running "./build/run_docker.sh make integration": https://gist.github.com/theresac23/eaa9a46539f6050b77ce6846c55e4ca8

I did peek into envoy.xdsv3.log and found a single error:
`[2020-07-29 16:21:17.834][1180][debug][init] [source/common/init/watcher_impl.cc:27] init manager Server destroyed
unable to bind domain socket with id=0 (see --base-id option)
`

**Comment by acnodal-tc** [comment] 2020-07-29 20:20
I think that error in the envoy log is indicative.  Looks like Envoy isn't cleaning up after itself when it exits the first set of tests so it can't open its domain sockets for the second set of tests.

Relevant issue: https://github.com/envoyproxy/envoy/issues/88

The question is why not?  I'll look into that question this evening.

**Comment by acnodal-tc** [comment] 2020-07-30 01:40
Looks like a race condition in integration.sh where it signals Envoy to exit but doesn't wait for it, so Envoy might still be running when the next test tries to start a different Envoy, causing conflicts with Envoy's domain sockets.

Attempt at a fix: https://github.com/acnodal/go-control-plane/commit/0631eadddb3ea4eceba8c7eaf37531829f13e947

I pushed a branch to acnodal's fork with that commit: https://github.com/acnodal/go-control-plane/tree/integration-test-race

@theresac23 I can't reproduce the problem reliably so could you please try the integration-test-race branch and see if that helps?

Thanks!

**Comment by kyessenov** [comment] 2020-08-13 17:07
Wait was added, so this should be fixed now. Re-open if you object.

**Closed by kyessenov** 2020-08-13 17:07 UTC

**Comment by acnodal-tc** [comment] 2020-08-13 17:52
LGTM, thanks!
